'iq'
--> type == 'get'
--> id == 'uid00000076'
--> xml:lang == 'en'
--> to == 'badblock3@warface/GameClient'
--> from == 'darkhero1@warface/GameClient'
'iq'
--> type == 'result'
--> id == 'uid0000011f'
--> xml:lang == 'en'
--> to == 'badblock3@warface/GameClient'
--> from == 'masterserver@warface/main_pve_1'

'gameroom_join'
--> code == '0'
--> room_id == '1623'

'players'
'player'
--> banner_stripe == '4294967295'
--> banner_mark == '4294967295'
--> banner_badge == '4294967295'
--> experience == '3614'
--> presence == '17'
--> online_id == 'bielolindo@warface/GameClient'
--> class_id == '0'
--> clanName == ''
--> nickname == 'VouuTeMateii'
--> observer == '0'
--> status == '0'
--> team_id == '0'
--> profile_id == '1517474'

'leaderboard'
--> league == '4'
--> position == '267'
--> max_performance == '49625'
--> profile_performance == '0'
--> stat == '2'

'player'
--> clan == ''
--> class == '3'
--> experience == '79446'
--> nickname == 'ShandonRoot'

'performance'
--> success == '-1'
--> mission_id == '86903b14-dba6-430a-b284-1fce51d00ed3'

'profile_progression_state'	
--> class_unlocked == '5'	
--> tutorial_passed == '1'	
--> tutorial_unlocked == '1'	
--> mission_unlocked == 'none,trainingmission,easyzombiemission,campaignsection1,all'	
--> profile_id == '1492947'	

'chat_channels'	
'chat'	
--> service_id == 'conference.warface'	
--> channel_id == 'global.main_pve_1'	
--> channel == '0'

'character'
--> banner_stripe == '4294967295'
--> banner_mark == '4294967295'
--> banner_badge == '4294967295'
--> experience == '135'
--> current_class == '0'
--> head == 'default_head_14'
--> fatness == '0'
--> height == '1'
--> gender == 'male'
--> nick == 'client1'

'server'
--> bootstrap == ''
--> max_rank == '70'
--> min_rank == '1'
--> online == '114'
--> quickplay_load == '0.170370'
--> load == '0.211111'
--> rank_group == 'skilled'
--##> channel == 'pve'
--> server_id == '5'
--> resource == 'main_pve_5'

'server'
--> bootstrap == ''
--> max_rank == '70'
--> min_rank == '20'
--> online == '430'
--> quickplay_load == '0.635185'
--> load == '0.796296'
--> rank_group == 'all'
--##> channel == 'pvp_pro'
--> server_id == '302'
--> resource == 'main_pvp_pro_2'

'gameroom_sync'	
'game_room'	
--> room_type == '1'	
--> room_id == '8807'

'core'	
--> revision == '5'	
--> team_balanced == '1'	
--> can_start == '0'	
--> players == '1'	
--> private == '0'	
--> room_name == 'Sala de jogo client1'	
--> teams_switched == '0'	

'gameroom_sync'	
'game_room'	
--> room_type == '1'	
--> room_id == '8807'	

'mission'	
--> revision == '4'	
--> time_of_day == '9:06'	
--> type == 'trainingmission'	
--> difficulty == 'easy'	
--> image == 'mapImgKosovo'	
--> description == '@pve_bp_end_path'	
--> mode_icon == 'pve_icon'	
--> mode_name == '@PvE_game_mode_desc'	
--> mode == 'pve'	
--> setting == 'kosovo/kosovo_base'	
--> name == '@bp_mission_easy02_1'	
--> no_teams == '1'	
--> mission_key == '86903b14-dba6-430a-b284-1fce51d00ed3'