WFX_MODULEID_UNKNOWN    = 0x1
WFX_MODULEID_HWIDBYPASS = 0x2
WFX_MODULEID_RESERVED1  = 0x4
WFX_MODULEID_RESERVED2  = 0x8

WFX_EVENTID_DRAW       = 0
WFX_EVENTID_PROJECTILEDIR  = 1
WFX_EVENTID_WINDOW_LOST_FOCUS = 2
WFX_EVENTID_KEYDOWN      = 3
WFX_EVENTID_KEYUP        = 4
WFX_EVENTID_LBUTTON_DOWN = 5
WFX_EVENTID_LBUTTON_UP   = 6
WFX_EVENTID_RBUTTON_DOWN = 7
WFX_EVENTID_RBUTTON_UP   = 8
WFX_EVENTID_VAC          = 9
WFX_EVENTID_RESERVED_EVENT1 = 10
WFX_EVENTID_RESERVED_EVENT2 = 11
WFX_EVENTID_WHEEL_DOWN   = 12
WFX_EVENTID_WHEEL_UP     = 13
WFX_EVENTID_MOUSEMOVE    = 14
WFX_EVENTID_ACTION       = 15

WFX_FUNCTION_ID_NORECOIL  = 0
WFX_FUNCTION_ID_NOSPREAD  = 1
WFX_FUNCTION_ID_VAC       = 2
WFX_FUNCTION_ID_ANTI_FLASH_GRENADE = 3
WFX_FUNCTION_ID_ENDLESS_RUNNING    = 4

WEAPON_ID_1ST = 0
WEAPON_ID_2ND = 1
WEAPON_ID_3RD = 2